from v2.nacos.utils.encode_util import bytes_to_str as bytes_to_str, decode_base64 as decode_base64, str_to_bytes as str_to_bytes

def pad(byte_array: bytes) -> bytes: ...
def unpad(byte_array: bytes) -> bytes: ...
def encrypt(message: str, key: str) -> str: ...
def decrypt(encr_data: str, key: str) -> str: ...
