from pydantic import BaseModel as BaseModel
from v2.nacos.common.constants import Constants as Constants

def get_current_time_millis(): ...
def to_json_string(obj: BaseModel): ...
def to_json_obj(body): ...
def to_json(obj): ...
def vars_obj(obj): ...
