def str_to_bytes(text: str, encoding: str = 'utf-8') -> bytes: ...
def bytes_to_str(bytes_, encoding: str = 'utf-8'): ...
def decode_base64(bytes_: bytes): ...
def encode_base64(bytes_): ...
def urlsafe_b64encode(bytes_): ...
