from _typeshed import Incomplete
from logging import Logger

os_type: Incomplete

def mkdir_if_necessary(create_dir: str): ...
def is_file_exist(file_path: str): ...
async def read_file(logger: Logger, file_path: str) -> str: ...
async def read_all_files_in_dir(logger: Logger, dir_path: str) -> dict | None: ...
async def write_to_file(logger: Logger, file_path: str, content: str) -> None: ...
