// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: review.proto

package trip_review_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TripReviewService_CreateReview_FullMethodName                  = "/trip_review_service.trip_review_service/CreateReview"
	TripReviewService_UpdateReview_FullMethodName                  = "/trip_review_service.trip_review_service/UpdateReview"
	TripReviewService_DeleteReview_FullMethodName                  = "/trip_review_service.trip_review_service/DeleteReview"
	TripReviewService_GetReviewByTargetID_FullMethodName           = "/trip_review_service.trip_review_service/GetReviewByTargetID"
	TripReviewService_GetReviewByTargetIDWithCursor_FullMethodName = "/trip_review_service.trip_review_service/GetReviewByTargetIDWithCursor"
)

// TripReviewServiceClient is the client API for TripReviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TripReviewServiceClient interface {
	CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewResponse, error)
	UpdateReview(ctx context.Context, in *UpdateReviewRequest, opts ...grpc.CallOption) (*UpdateReviewResponse, error)
	DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*DeleteReviewResponse, error)
	GetReviewByTargetID(ctx context.Context, in *GetReviewByTargetIDRequest, opts ...grpc.CallOption) (*GetReviewByTargetIDResponse, error)
	GetReviewByTargetIDWithCursor(ctx context.Context, in *GetReviewByTargetIDWithCursorRequest, opts ...grpc.CallOption) (*GetReviewByTargetIDWithCursorResponse, error)
}

type tripReviewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTripReviewServiceClient(cc grpc.ClientConnInterface) TripReviewServiceClient {
	return &tripReviewServiceClient{cc}
}

func (c *tripReviewServiceClient) CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReviewResponse)
	err := c.cc.Invoke(ctx, TripReviewService_CreateReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripReviewServiceClient) UpdateReview(ctx context.Context, in *UpdateReviewRequest, opts ...grpc.CallOption) (*UpdateReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateReviewResponse)
	err := c.cc.Invoke(ctx, TripReviewService_UpdateReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripReviewServiceClient) DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*DeleteReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteReviewResponse)
	err := c.cc.Invoke(ctx, TripReviewService_DeleteReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripReviewServiceClient) GetReviewByTargetID(ctx context.Context, in *GetReviewByTargetIDRequest, opts ...grpc.CallOption) (*GetReviewByTargetIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReviewByTargetIDResponse)
	err := c.cc.Invoke(ctx, TripReviewService_GetReviewByTargetID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripReviewServiceClient) GetReviewByTargetIDWithCursor(ctx context.Context, in *GetReviewByTargetIDWithCursorRequest, opts ...grpc.CallOption) (*GetReviewByTargetIDWithCursorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReviewByTargetIDWithCursorResponse)
	err := c.cc.Invoke(ctx, TripReviewService_GetReviewByTargetIDWithCursor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TripReviewServiceServer is the server API for TripReviewService service.
// All implementations must embed UnimplementedTripReviewServiceServer
// for forward compatibility.
type TripReviewServiceServer interface {
	CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewResponse, error)
	UpdateReview(context.Context, *UpdateReviewRequest) (*UpdateReviewResponse, error)
	DeleteReview(context.Context, *DeleteReviewRequest) (*DeleteReviewResponse, error)
	GetReviewByTargetID(context.Context, *GetReviewByTargetIDRequest) (*GetReviewByTargetIDResponse, error)
	GetReviewByTargetIDWithCursor(context.Context, *GetReviewByTargetIDWithCursorRequest) (*GetReviewByTargetIDWithCursorResponse, error)
	mustEmbedUnimplementedTripReviewServiceServer()
}

// UnimplementedTripReviewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTripReviewServiceServer struct{}

func (UnimplementedTripReviewServiceServer) CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReview not implemented")
}
func (UnimplementedTripReviewServiceServer) UpdateReview(context.Context, *UpdateReviewRequest) (*UpdateReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateReview not implemented")
}
func (UnimplementedTripReviewServiceServer) DeleteReview(context.Context, *DeleteReviewRequest) (*DeleteReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteReview not implemented")
}
func (UnimplementedTripReviewServiceServer) GetReviewByTargetID(context.Context, *GetReviewByTargetIDRequest) (*GetReviewByTargetIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReviewByTargetID not implemented")
}
func (UnimplementedTripReviewServiceServer) GetReviewByTargetIDWithCursor(context.Context, *GetReviewByTargetIDWithCursorRequest) (*GetReviewByTargetIDWithCursorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReviewByTargetIDWithCursor not implemented")
}
func (UnimplementedTripReviewServiceServer) mustEmbedUnimplementedTripReviewServiceServer() {}
func (UnimplementedTripReviewServiceServer) testEmbeddedByValue()                           {}

// UnsafeTripReviewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TripReviewServiceServer will
// result in compilation errors.
type UnsafeTripReviewServiceServer interface {
	mustEmbedUnimplementedTripReviewServiceServer()
}

func RegisterTripReviewServiceServer(s grpc.ServiceRegistrar, srv TripReviewServiceServer) {
	// If the following call panics, it indicates UnimplementedTripReviewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TripReviewService_ServiceDesc, srv)
}

func _TripReviewService_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripReviewServiceServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripReviewService_CreateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripReviewServiceServer).CreateReview(ctx, req.(*CreateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripReviewService_UpdateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripReviewServiceServer).UpdateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripReviewService_UpdateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripReviewServiceServer).UpdateReview(ctx, req.(*UpdateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripReviewService_DeleteReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripReviewServiceServer).DeleteReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripReviewService_DeleteReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripReviewServiceServer).DeleteReview(ctx, req.(*DeleteReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripReviewService_GetReviewByTargetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewByTargetIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripReviewServiceServer).GetReviewByTargetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripReviewService_GetReviewByTargetID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripReviewServiceServer).GetReviewByTargetID(ctx, req.(*GetReviewByTargetIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripReviewService_GetReviewByTargetIDWithCursor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewByTargetIDWithCursorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripReviewServiceServer).GetReviewByTargetIDWithCursor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripReviewService_GetReviewByTargetIDWithCursor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripReviewServiceServer).GetReviewByTargetIDWithCursor(ctx, req.(*GetReviewByTargetIDWithCursorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TripReviewService_ServiceDesc is the grpc.ServiceDesc for TripReviewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TripReviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trip_review_service.trip_review_service",
	HandlerType: (*TripReviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReview",
			Handler:    _TripReviewService_CreateReview_Handler,
		},
		{
			MethodName: "UpdateReview",
			Handler:    _TripReviewService_UpdateReview_Handler,
		},
		{
			MethodName: "DeleteReview",
			Handler:    _TripReviewService_DeleteReview_Handler,
		},
		{
			MethodName: "GetReviewByTargetID",
			Handler:    _TripReviewService_GetReviewByTargetID_Handler,
		},
		{
			MethodName: "GetReviewByTargetIDWithCursor",
			Handler:    _TripReviewService_GetReviewByTargetIDWithCursor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review.proto",
}
