# https://taskfile.dev

version: '3'

tasks:
  gen-proto:
    desc: Generate protobuf and gRPC codes for user service
    cmds:
      - mkdir -p src/main/proto
      - cp ../contracts/protobuf/tripsphere/user/*.proto src/main/proto/
      - ./mvnw protobuf:compile protobuf:compile-custom
