# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
    silent: true

  gen-proto:
    desc: Generate protobuf and gRPC codes
    sources:
      - ../contracts/protobuf/**/*.proto
    generates:
      - target/generated-sources/protobuf/java/**/*.java
      - target/generated-sources/protobuf/grpc-java/**/*.java
    cmds:
      - rm -rf src/main/proto
      - cp -r ../contracts/protobuf/ src/main/proto/
      - cmd: mvnw protobuf:compile protobuf:compile-custom
        platforms: [windows]
      - cmd: chmod +x mvnw
        platforms: [linux, darwin]
      - cmd: ./mvnw protobuf:compile protobuf:compile-custom
        platforms: [linux, darwin]

  build:
    desc: Build Docker image
    vars:
      PREFIX: '{{.PREFIX | default "tripsphere"}}'
      TAG: '{{.TAG | default "latest"}}'
    cmds:
      - docker build . -t {{.PREFIX}}/trip-user-service:{{.TAG}}

  build-aliyun:
    desc: Build Docker image with Aliyun mirror
    vars:
      PREFIX: '{{.PREFIX | default "tripsphere"}}'
      TAG: '{{.TAG | default "latest"}}'
    cmd: |
        docker build . -t {{.PREFIX}}/trip-user-service:{{.TAG}} \
        --build-arg ALIYUN_MIRROR=true

  format:
    desc: Format Java code using spotless
    cmds:
      - cmd: mvnw spotless:apply
        platforms: [windows]
      - cmd: ./mvnw spotless:apply
        platforms: [linux, darwin]
