# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
    silent: true

  gen-proto:
    desc: Generate protobuf and gRPC codes
    sources:
      - ../contracts/protobuf/**/*.proto
    generates:
      - target/generated-sources/protobuf/java/**/*.java
      - target/generated-sources/protobuf/grpc-java/**/*.java
    cmds:
      - rm -rf src/main/proto
      - cp -r ../contracts/protobuf/ src/main/proto/
      - cmd: mvnw protobuf:compile protobuf:compile-custom
        platforms: [windows]
      - cmd: ./mvnw protobuf:compile protobuf:compile-custom
        platforms: [linux, darwin]

  build:
    desc: Build Docker image
    vars:
      PREFIX: '{{.PREFIX | default "tripsphere"}}'
      TAG: '{{.TAG | default "latest"}}'
    cmds:
      - docker build . -t {{.PREFIX}}/trip-user-service:{{.TAG}}

  format:
    desc: Format Java code using spotless
    cmds:
      - cmd: mvnw spotless:apply
        platforms: [windows]
      - cmd: ./mvnw spotless:apply
        platforms: [linux, darwin]

  run:
    desc: Run the application with local profile
    aliases: [run-local]
    cmds:
      - echo "Not Implemented Yet"

  run-dev:
    desc: Run the application with development profile
    cmds:
      - echo "Not Implemented Yet"
