spring:
  application:
    name: trip-attraction-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        metadata:
          gRPC_port: ${grpc.server.port:50053}
          protocol: grpc
  data:
    mongodb:
      uri: mongodb://root:fudanse@localhost:27017
      database: attraction_db

server:
  port: 24213

grpc:
  server:
    port: 50053
    enable-reflection: true

logging:
  level:
    org.tripsphere.attraction: DEBUG
    net.devh.boot.grpc: INFO
