# https://taskfile.dev

version: '3'

vars:
  PROTO_SRC_DIR: contracts/protobuf

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
    silent: true
  
  buf:
    desc: Run buf format and buf lint
    dir: contracts/protobuf
    cmds:
      - buf format --write
      - buf lint

  gen-proto:
    desc: Generate protobuf codes using buf
    dir: contracts/protobuf
    cmds:
      - echo Not Implemented Yet

  docker-gen-proto:
    desc: Generate protobuf codes using buf Docker image
    dir: contracts/protobuf
    cmds:
      - echo Not Implemented Yet

  start:
    desc: Start all the services using Docker Compose
    cmds:
      - echo Not Implemented Yet
