# https://taskfile.dev

version: '3'

includes:
  attraction:
    taskfile: trip-attraction-service/Taskfile.yaml
    dir: trip-attraction-service
    internal: true

  chat:
    taskfile: trip-chat-service/Taskfile.yaml
    dir: trip-chat-service
    internal: true

  file:
    taskfile: trip-file-service/Taskfile.yaml
    dir: trip-file-service
    internal: true

  hotel:
    taskfile: trip-hotel-service/Taskfile.yaml
    dir: trip-hotel-service
    internal: true

  itinerary-planner:
    taskfile: trip-itinerary-planner/Taskfile.yaml
    dir: trip-itinerary-planner
    internal: true

  itinerary:
    taskfile: trip-itinerary-service/Taskfile.yaml
    dir: trip-itinerary-service
    internal: true

  journey-assistant:
    taskfile: trip-journey-assistant/Taskfile.yaml
    dir: trip-journey-assistant
    internal: true

  next-frontend:
    taskfile: trip-next-frontend/Taskfile.yaml
    dir: trip-next-frontend
    internal: true

  note:
    taskfile: trip-note-service/Taskfile.yaml
    dir: trip-note-service
    internal: true

  review:
    taskfile: trip-review-service/Taskfile.yaml
    dir: trip-review-service
    internal: true

  review-summary:
    taskfile: trip-review-summary/Taskfile.yaml
    dir: trip-review-summary
    internal: true

  user:
    taskfile: trip-user-service/Taskfile.yaml
    dir: trip-user-service
    internal: true

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
    silent: true
  
  buf:
    desc: Run buf format and buf lint
    dir: contracts
    cmds:
      - buf format --write
      - buf lint

  gen-proto:
    desc: Generate protobuf and gRPC codes
    cmds:
      - task: attraction:gen-proto
      - task: chat:gen-proto
      - task: file:gen-proto
      - task: hotel:gen-proto
      - task: itinerary-planner:gen-proto
      - task: itinerary:gen-proto
      - task: journey-assistant:gen-proto
      - task: next-frontend:gen-proto
      - task: note:gen-proto
      - task: review:gen-proto
      - task: review-summary:gen-proto
      - task: user:gen-proto

  build:
    desc: Build Docker images for all services
    cmds:
      - task: attraction:build
      - task: chat:build
      - task: file:build
      - task: hotel:build
      - task: itinerary-planner:build
      - task: itinerary:build
      - task: journey-assistant:build
      - task: next-frontend:build
      - task: note:build
      - task: review:build
      - task: review-summary:build
      - task: user:build

  start:
    desc: Start all services using Docker Compose
    cmds:
      - docker compose up -d --force-recreate --remove-orphans

  stop:
    desc: Stop all services using Docker Compose
    cmds:
      - echo Not Implemented Yet
