from v2.nacos.transport.model.rpc_response import Response as Response

class NotifySubscriberResponse(Response):
    def get_response_type(self) -> str: ...

class ConnectResetResponse(Response):
    def get_response_type(self) -> str: ...

class ClientDetectionResponse(Response):
    def get_response_type(self) -> str: ...

class ServerCheckResponse(Response):
    connectionId: str | None
    def get_response_type(self) -> str: ...
    def set_connection_id(self, connection_id: str) -> None: ...
    def get_connection_id(self) -> str: ...

class HealthCheckResponse(Response):
    def get_response_type(self): ...

class ErrorResponse(Response):
    def get_response_type(self): ...
