import abc
from abc import ABC, abstractmethod
from pydantic import BaseModel

class Response(BaseModel, ABC, metaclass=abc.ABCMeta):
    resultCode: int
    errorCode: int
    message: str
    requestId: str
    @classmethod
    def convert(cls, obj: object): ...
    def set_request_id(self, request_id: str): ...
    def is_success(self) -> bool: ...
    def get_error_code(self) -> int: ...
    def get_result_code(self) -> int: ...
    def get_message(self) -> str: ...
    @abstractmethod
    def get_response_type(self) -> str: ...
