import abc
from abc import ABC, abstractmethod
from pydantic import BaseModel

class Request(BaseModel, ABC, metaclass=abc.ABCMeta):
    headers: dict
    requestId: str
    module: str
    def put_all_headers(self, headers: dict): ...
    def put_header(self, key: str, value: str) -> None: ...
    def clear_headers(self) -> None: ...
    def get_header(self, key: str, default_value=None) -> str: ...
    def get_headers(self) -> dict: ...
    def get_request_id(self) -> str: ...
    @abstractmethod
    def get_module(self) -> str: ...
    @abstractmethod
    def get_request_type(self) -> str: ...
