from _typeshed import Incomplete
from v2.nacos.common.constants import Constants as Constants

class ServerInfo:
    server_ip: Incomplete
    server_port: Incomplete
    def __init__(self, server_ip: str, server_port: int) -> None: ...
    def get_address(self): ...
    def get_server_ip(self): ...
    def set_server_ip(self, server_ip) -> None: ...
    def get_server_port(self): ...
    def set_server_port(self, server_port) -> None: ...
