# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
    silent: true

  gen-proto:
    desc: Generate protobuf and gRPC codes using buf
    sources:
      - ../contracts/protobuf/**/*.proto
    generates:
      - lib/grpc/gen/**/*.ts
    cmds:
      - buf generate

  format:
    desc: Format code with Prettier
    cmds:
      - bunx prettier . --write

  build:
    desc: Build Docker image
    vars:
      PREFIX: '{{.PREFIX | default "tripsphere"}}'
      TAG: '{{.TAG | default "latest"}}'
    cmds:
      - docker build . -t {{.PREFIX}}/trip-next-frontend:{{.TAG}}
