# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
    silent: true

  gen-proto:
    desc: Generate protobuf and gRPC codes using protoc
    cmds:
      - cmd: bash scripts/gen-proto.sh
        platforms: [linux, darwin]
      - cmd: powershell -File scripts/gen-proto.ps1
        platforms: [windows]
    silent: true
