import abc
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from v2.nacos.transport.model.rpc_request import Request as Request
from v2.nacos.transport.model.rpc_response import Response as Response
from v2.nacos.transport.model.server_info import ServerInfo as ServerInfo

class IConnection(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def request(self, request: Request, timeout_mills: int) -> Response: ...
    @abstractmethod
    def close(self): ...

class Connection(IConnection, ABC, metaclass=abc.ABCMeta):
    connection_id: Incomplete
    abandon: bool
    server_info: Incomplete
    def __init__(self, connection_id, server_info: ServerInfo) -> None: ...
    def get_connection_id(self) -> str: ...
    def get_server_info(self) -> ServerInfo: ...
    def set_abandon(self, flag: bool): ...
    def is_abandon(self): ...
