from _typeshed import Incomplete
from v2.nacos.common.client_config import ClientConfig as ClientConfig
from v2.nacos.common.nacos_exception import CLIENT_INVALID_PARAM as CLIENT_INVALID_PARAM, INVALID_PARAM as INVALID_PARAM, NacosException as NacosException
from v2.nacos.transport.grpc_client import GrpcClient as GrpcClient
from v2.nacos.transport.nacos_server_connector import NacosServerConnector as NacosServerConnector
from v2.nacos.transport.rpc_client import ConnectionType as ConnectionType, RpcClient as RpcClient

class RpcClientFactory:
    client_map: Incomplete
    logger: Incomplete
    lock: Incomplete
    def __init__(self, logger) -> None: ...
    def get_all_client_entries(self) -> dict[str, RpcClient]: ...
    def get_client(self, client_name: str) -> RpcClient: ...
    async def create_client(self, client_name: str, connection_type: ConnectionType, labels: dict[str, str], client_config: ClientConfig, nacos_server: NacosServerConnector) -> RpcClient: ...
    async def shutdown_all_clients(self) -> None: ...

def get_app_labels_from_env() -> dict: ...
def parse_labels(raw_labels: str) -> dict: ...
def merge_app_labels(app_labels_appointed: dict, app_labels_env: dict) -> dict: ...
def merge_maps(map1: dict, map2: dict, prefer_first: bool) -> dict: ...
def add_prefix_for_each_key(m: dict, prefix: str) -> dict: ...
