import abc
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from enum import Enum
from v2.nacos.common.constants import Constants as Constants
from v2.nacos.common.nacos_exception import CLIENT_DISCONNECT as CLIENT_DISCONNECT, NacosException as NacosException, SERVER_ERROR as SERVER_ERROR, UN_REGISTER as UN_REGISTER
from v2.nacos.transport.connection import Connection as Connection
from v2.nacos.transport.connection_event_listener import ConnectionEventListener as ConnectionEventListener
from v2.nacos.transport.model.internal_request import CLIENT_DETECTION_REQUEST_TYPE as CLIENT_DETECTION_REQUEST_TYPE, CONNECTION_RESET_REQUEST_TYPE as CONNECTION_RESET_REQUEST_TYPE, ConnectResetRequest as ConnectResetRequest, HealthCheckRequest as HealthCheckRequest
from v2.nacos.transport.model.internal_response import ConnectResetResponse as ConnectResetResponse, ErrorResponse as ErrorResponse
from v2.nacos.transport.model.rpc_request import Request as Request
from v2.nacos.transport.model.server_info import ServerInfo as ServerInfo
from v2.nacos.transport.nacos_server_connector import NacosServerConnector as NacosServerConnector
from v2.nacos.transport.server_request_handler import ClientDetectionRequestHandler as ClientDetectionRequestHandler, IServerRequestHandler as IServerRequestHandler
from v2.nacos.utils.common_util import get_current_time_millis as get_current_time_millis

class ConnectionType(Enum):
    GRPC = ...

class RpcClientStatus(Enum):
    INITIALIZED = ...
    STARTING = ...
    UNHEALTHY = ...
    RUNNING = ...
    SHUTDOWN = ...

class ConnectionStatus(Enum):
    DISCONNECTED = ...
    CONNECTED = ...

class ConnectionEvent:
    event_type: Incomplete
    def __init__(self, event_type: ConnectionStatus) -> None: ...
    def is_connected(self) -> bool: ...
    def is_disconnected(self) -> bool: ...

class ReconnectContext:
    on_request_fail: Incomplete
    server_info: Incomplete
    def __init__(self, server_info: ServerInfo | None, on_request_fail: bool) -> None: ...

class RpcClient(ABC, metaclass=abc.ABCMeta):
    RETRY_TIMES: int
    DEFAULT_TIMEOUT_MILLS: int
    logger: Incomplete
    name: Incomplete
    labels: dict[str, str]
    current_connection: Incomplete
    rpc_client_status: Incomplete
    event_chan: Incomplete
    reconnection_chan: Incomplete
    connection_event_listeners: Incomplete
    server_request_handler_mapping: Incomplete
    nacos_server: Incomplete
    tenant: Incomplete
    lock: Incomplete
    last_active_timestamp: Incomplete
    event_listener_task: Incomplete
    health_check_task: Incomplete
    reconnection_task: Incomplete
    def __init__(self, logger, name: str, nacos_server: NacosServerConnector) -> None: ...
    def put_all_labels(self, labels: dict[str, str]): ...
    async def event_listener(self) -> None: ...
    async def health_check_periodically(self) -> None: ...
    async def reconnection_handler(self) -> None: ...
    async def start(self) -> None: ...
    @abstractmethod
    async def connect_to_server(self, server_info: ServerInfo) -> Connection | None: ...
    @abstractmethod
    def get_connection_type(self): ...
    @abstractmethod
    def get_rpc_port_offset(self): ...
    def get_current_server(self): ...
    async def switch_server_async(self, server_info: ServerInfo | None, on_request_fail: bool): ...
    def is_wait_initiated(self): ...
    def is_running(self): ...
    def is_shutdown(self): ...
    async def notify_server_srv_change(self) -> None: ...
    async def register_server_request_handlers(self) -> None: ...
    async def register_server_request_handler(self, request_type: str, handler: IServerRequestHandler) -> None: ...
    async def register_connection_listener(self, listener: ConnectionEventListener): ...
    async def request(self, request: Request, timeout_millis: int = ...): ...
    async def shutdown(self) -> None: ...
    async def send_health_check(self): ...
    async def reconnect(self, reconnection_ctx: ReconnectContext): ...

class ConnectResetRequestHandler(IServerRequestHandler):
    rpc_client: Incomplete
    def __init__(self, rpc_client: RpcClient) -> None: ...
    def name(self) -> str: ...
    async def request_reply(self, request: Request) -> ConnectResetResponse | None: ...
