spring:
  application:
    name: trip-user-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        metadata:
          gRPC_port: ${grpc.server.port:50056}
          protocol: grpc
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: fudanse
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 24217

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    console: "level=%-5level timestamp=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} service=trip-user-service trace_id=%X{trace_id:-} span_id=%X{span_id:-} logger=%logger{36} message=%msg%n"

grpc:
  server:
    port: 50056
    enable-reflection: true

jwt:
  private-key: classpath:keys/private.pem
  public-key: classpath:keys/public.pem
  expiration: 86400000
