# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
    silent: true

  install:
    desc: Set up project development environment
    cmds:
      - uv sync  # Install dependencies and dev-dependencies
      - task: gen-proto
      - task: otel-instr

  otel-instr:
    desc: Install OpenTelemetry instrumentation packages
    cmd: |
      uv run opentelemetry-bootstrap -a requirements \
        | uv pip install --requirements -

  gen-proto:
    desc: Generate protobuf and gRPC codes using buf
    sources:
      - ../contracts/protobuf/**/*.proto
    generates:
      - libs/tripsphere/src/**/*_pb2.py
      - libs/tripsphere/src/**/*_pb2_grpc.py
    cmds:
      - buf generate

  protoc-gen:
    desc: Generate protobuf and gRPC codes using grpcio-tools
    sources:
      - ../contracts/protobuf/**/*.proto
    generates:
      - libs/tripsphere/src/**/*_pb2.py
      - libs/tripsphere/src/**/*_pb2_grpc.py
    cmds:
      - for: sources
        cmd: |
          uv run --locked --no-sync --with 'grpcio-tools' \
            --with 'mypy-protobuf' -m grpc_tools.protoc \
            -I../contracts/protobuf \
            --python_out=libs/tripsphere/src \
            --grpc_python_out=libs/tripsphere/src \
            --mypy_out=libs/tripsphere/src \
            --mypy_grpc_out=libs/tripsphere/src \
            "{{.ITEM}}"
    silent: true

  build:
    desc: Build Docker image
    vars:
      PREFIX: '{{.PREFIX | default "tripsphere"}}'
      TAG: '{{.TAG | default "latest"}}'
    cmds:
      - docker build . -t {{.PREFIX}}/trip-review-summary:{{.TAG}}

  build-aliyun:
    desc: Build Docker image with Aliyun PyPI mirror
    vars:
      PREFIX: '{{.PREFIX | default "tripsphere"}}'
      TAG: '{{.TAG | default "latest"}}'
    cmds:
      - mv uv.lock uv.lock.backup
      - defer: mv uv.lock.backup uv.lock
      - uv lock --default-index https://mirrors.aliyun.com/pypi/simple
      - docker build . -t {{.PREFIX}}/trip-review-summary:{{.TAG}}

  ruff:
    desc: Run ruff format and ruff check --fix
    cmds:
      - uvx ruff format
      - uvx ruff check --fix
