# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tripsphere.attraction.attraction_pb2 as attraction__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in attraction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AttractionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddAttraction = channel.unary_unary(
                '/org.tripsphere.attraction.AttractionService/AddAttraction',
                request_serializer=attraction__pb2.AddAttractionRequest.SerializeToString,
                response_deserializer=attraction__pb2.AddAttractionResponse.FromString,
                _registered_method=True)
        self.DeleteAttraction = channel.unary_unary(
                '/org.tripsphere.attraction.AttractionService/DeleteAttraction',
                request_serializer=attraction__pb2.DeleteAttractionRequest.SerializeToString,
                response_deserializer=attraction__pb2.DeleteAttractionResponse.FromString,
                _registered_method=True)
        self.ChangeAttraction = channel.unary_unary(
                '/org.tripsphere.attraction.AttractionService/ChangeAttraction',
                request_serializer=attraction__pb2.ChangeAttractionRequest.SerializeToString,
                response_deserializer=attraction__pb2.ChangeAttractionResponse.FromString,
                _registered_method=True)
        self.FindIdByName = channel.unary_unary(
                '/org.tripsphere.attraction.AttractionService/FindIdByName',
                request_serializer=attraction__pb2.FindIdByNameRequest.SerializeToString,
                response_deserializer=attraction__pb2.FindIdByNameResponse.FromString,
                _registered_method=True)


class AttractionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddAttraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAttraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeAttraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindIdByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttractionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddAttraction': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAttraction,
                    request_deserializer=attraction__pb2.AddAttractionRequest.FromString,
                    response_serializer=attraction__pb2.AddAttractionResponse.SerializeToString,
            ),
            'DeleteAttraction': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAttraction,
                    request_deserializer=attraction__pb2.DeleteAttractionRequest.FromString,
                    response_serializer=attraction__pb2.DeleteAttractionResponse.SerializeToString,
            ),
            'ChangeAttraction': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeAttraction,
                    request_deserializer=attraction__pb2.ChangeAttractionRequest.FromString,
                    response_serializer=attraction__pb2.ChangeAttractionResponse.SerializeToString,
            ),
            'FindIdByName': grpc.unary_unary_rpc_method_handler(
                    servicer.FindIdByName,
                    request_deserializer=attraction__pb2.FindIdByNameRequest.FromString,
                    response_serializer=attraction__pb2.FindIdByNameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.tripsphere.attraction.AttractionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('org.tripsphere.attraction.AttractionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttractionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddAttraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.tripsphere.attraction.AttractionService/AddAttraction',
            attraction__pb2.AddAttractionRequest.SerializeToString,
            attraction__pb2.AddAttractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAttraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.tripsphere.attraction.AttractionService/DeleteAttraction',
            attraction__pb2.DeleteAttractionRequest.SerializeToString,
            attraction__pb2.DeleteAttractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeAttraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.tripsphere.attraction.AttractionService/ChangeAttraction',
            attraction__pb2.ChangeAttractionRequest.SerializeToString,
            attraction__pb2.ChangeAttractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindIdByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.tripsphere.attraction.AttractionService/FindIdByName',
            attraction__pb2.FindIdByNameRequest.SerializeToString,
            attraction__pb2.FindIdByNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
