from _typeshed import Incomplete
from v2.nacos.common.client_config import ClientConfig as ClientConfig
from v2.nacos.common.constants import Constants as Constants
from v2.nacos.config.encryption.kms_handler import KMSHandler as KMSHandler
from v2.nacos.config.filter.config_filter import IConfigFilter as IConfigFilter
from v2.nacos.config.model.config_param import ConfigParam as ConfigParam, HandlerParam as HandlerParam, UsageType as UsageType

class ConfigEncryptionFilter(IConfigFilter):
    kms_handler: Incomplete
    def __init__(self, client_config: ClientConfig) -> None: ...
    def do_filter(self, param: ConfigParam) -> None: ...
    def get_order(self) -> int: ...
    def get_filter_name(self) -> str: ...
