import abc
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from v2.nacos.config.model.config_param import ConfigParam as ConfigParam

class IConfigFilter(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def do_filter(self, config_param): ...
    @abstractmethod
    def get_order(self): ...
    @abstractmethod
    def get_filter_name(self): ...

class ConfigFilterChainManager:
    config_filters: Incomplete
    def __init__(self) -> None: ...
    def add_filter(self, conf_filter: IConfigFilter) -> None: ...
    def get_filters(self) -> list[IConfigFilter]: ...
    def do_filters(self, param: ConfigParam) -> None: ...
    def do_filter_by_name(self, param: ConfigParam, name: str) -> None: ...
