from pydantic import BaseModel
from v2.nacos.common.constants import Constants as Constants
from v2.nacos.common.nacos_exception import INVALID_PARAM as INVALID_PARAM, NacosException as NacosException
from v2.nacos.common.preserved_metadata_key import PreservedMetadataKeys as PreservedMetadataKeys

class Instance(BaseModel):
    instanceId: str
    ip: str
    port: int
    weight: float
    healthy: bool
    enabled: bool
    ephemeral: bool
    clusterName: str
    serviceName: str
    metadata: dict
    def to_inet_addr(self): ...
    def is_ephemeral(self) -> bool: ...
    def get_weight(self): ...
    def add_metadata(self, key: str, value: str) -> None: ...
    def get_instance_heart_beat_interval(self): ...
    def get_instance_heart_beat_timeout(self): ...
    def get_ip_delete_timeout(self): ...
    def get_instance_id_generator(self): ...
    def check_instance_is_legal(self) -> None: ...
    def contains_metadata(self, key: str) -> bool: ...
