spring:
  application:
    name: trip-order-service
  profiles:
    active: dev

server:
  port: 24222

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.tripsphere.order: INFO
  pattern:
    console: "level=%-5level timestamp=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} service=trip-order-service trace_id=%X{trace_id:-} span_id=%X{span_id:-} logger=%logger{36} message=%msg%n"
