spring:
  application:
    name: trip-hotel-service
  cloud:
    nacos:
      server-addr: localhost:8848
  data:
    mongodb:
      uri: mongodb://root:fudanse@localhost:27017
      database: hotel_db

server:
  port: 24214

grpc:
  server:
    port: 50054
    enable-reflection: true
