services:
  nacos:
    image: nacos/nacos-server:v2.5.1
    container_name: nacos
    environment:
      - MODE=standalone
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"

networks:
  default:
    external:
      name: tripsphere