from _typeshed import Incomplete
from alibabacloud_kms20160120.client import Client
from v2.nacos.common.client_config import KMSConfig as KMSConfig
from v2.nacos.utils.encode_util import bytes_to_str as bytes_to_str

class KmsClient:
    client: Incomplete
    def __init__(self, client: Client) -> None: ...
    @staticmethod
    def create_kms_client(kms_config: KMSConfig): ...
    def encrypt(self, content: str, key_id: str): ...
    def decrypt(self, content: str): ...
    def generate_secret_key(self, key_id: str, key_spec: str): ...
