from _typeshed import Incomplete

class Credentials:
    access_key_id: Incomplete
    access_key_secret: Incomplete
    security_token: Incomplete
    def __init__(self, access_key_id, access_key_secret, security_token=None) -> None: ...
    def get_access_key_id(self): ...
    def get_access_key_secret(self): ...
    def get_security_token(self): ...

class CredentialsProvider:
    def get_credentials(self) -> None: ...

class StaticCredentialsProvider(CredentialsProvider):
    credentials: Incomplete
    def __init__(self, access_key_id: str = '', access_key_secret: str = '', security_token: str = '') -> None: ...
    def get_credentials(self): ...
    def set_access_key_id(self, access_key_id) -> None: ...
    def set_access_key_secret(self, access_key_secret) -> None: ...
