from v2.nacos.common.auth import CredentialsProvider as CredentialsProvider, StaticCredentialsProvider as StaticCredentialsProvider
from v2.nacos.common.client_config import ClientConfig as ClientConfig, GRPCConfig as GRPCConfig, KMSConfig as KMSConfig, TLSConfig as TLSConfig
from v2.nacos.common.constants import Constants as Constants

class ClientConfigBuilder:
    def __init__(self) -> None: ...
    def server_address(self, server_address: str) -> ClientConfigBuilder: ...
    def endpoint(self, endpoint) -> ClientConfigBuilder: ...
    def namespace_id(self, namespace_id: str) -> ClientConfigBuilder: ...
    def timeout_ms(self, timeout_ms) -> ClientConfigBuilder: ...
    def heart_beat_interval(self, heart_beat_interval) -> ClientConfigBuilder: ...
    def log_level(self, log_level) -> ClientConfigBuilder: ...
    def log_dir(self, log_dir: str) -> ClientConfigBuilder: ...
    def access_key(self, access_key: str) -> ClientConfigBuilder: ...
    def secret_key(self, secret_key: str) -> ClientConfigBuilder: ...
    def credentials_provider(self, credentials_provider: CredentialsProvider) -> ClientConfigBuilder: ...
    def username(self, username: str) -> ClientConfigBuilder: ...
    def password(self, password: str) -> ClientConfigBuilder: ...
    def cache_dir(self, cache_dir: str) -> ClientConfigBuilder: ...
    def tls_config(self, tls_config: TLSConfig) -> ClientConfigBuilder: ...
    def kms_config(self, kms_config: KMSConfig) -> ClientConfigBuilder: ...
    def grpc_config(self, grpc_config: GRPCConfig) -> ClientConfigBuilder: ...
    def load_cache_at_start(self, load_cache_at_start: bool) -> ClientConfigBuilder: ...
    def app_conn_labels(self, app_conn_labels: dict) -> ClientConfigBuilder: ...
    def endpoint_query_header(self, endpoint_query_header: dict[str, str]) -> ClientConfigBuilder: ...
    def build(self) -> ClientConfig: ...
