class PayloadRegistry:
    @classmethod
    def init(cls, payloads) -> None: ...
    @classmethod
    def scan(cls) -> None: ...
    @classmethod
    def register(cls, type_name, clazz) -> None: ...
    @classmethod
    def get_class_by_type(cls, type_name): ...
