from _typeshed import Incomplete
from v2.nacos.common.client_config import ClientConfig as ClientConfig
from v2.nacos.common.constants import Constants as Constants
from v2.nacos.common.nacos_exception import NacosException as NacosException, SERVER_ERROR as SERVER_ERROR
from v2.nacos.naming.cache.service_info_cache import ServiceInfoCache as ServiceInfoCache
from v2.nacos.naming.model.instance import Instance as Instance
from v2.nacos.naming.model.naming_param import ListServiceParam as ListServiceParam
from v2.nacos.naming.model.naming_request import AbstractNamingRequest as AbstractNamingRequest, BatchInstanceRequest as BatchInstanceRequest, InstanceRequest as InstanceRequest, NOTIFY_SUBSCRIBER_REQUEST_TYPE as NOTIFY_SUBSCRIBER_REQUEST_TYPE, PersistentInstanceRequest as PersistentInstanceRequest, ServiceListRequest as ServiceListRequest, SubscribeServiceRequest as SubscribeServiceRequest
from v2.nacos.naming.model.naming_response import BatchInstanceResponse as BatchInstanceResponse, InstanceResponse as InstanceResponse, ServiceListResponse as ServiceListResponse, SubscribeServiceResponse as SubscribeServiceResponse
from v2.nacos.naming.model.service import Service as Service, ServiceList as ServiceList
from v2.nacos.naming.remote.naming_grpc_connection_event_listener import NamingGrpcConnectionEventListener as NamingGrpcConnectionEventListener
from v2.nacos.naming.remote.naming_push_request_handler import NamingPushRequestHandler as NamingPushRequestHandler
from v2.nacos.naming.util.naming_client_util import get_group_name as get_group_name
from v2.nacos.naming.util.naming_remote_constants import NamingRemoteConstants as NamingRemoteConstants
from v2.nacos.transport.http_agent import HttpAgent as HttpAgent
from v2.nacos.transport.nacos_server_connector import NacosServerConnector as NacosServerConnector
from v2.nacos.transport.rpc_client import ConnectionType as ConnectionType
from v2.nacos.transport.rpc_client_factory import RpcClientFactory as RpcClientFactory
from v2.nacos.utils.common_util import get_current_time_millis as get_current_time_millis, to_json_string as to_json_string

class NamingGRPCClientProxy:
    DEFAULT_SERVER_PORT: int
    logger: Incomplete
    client_config: Incomplete
    uuid: Incomplete
    service_info_cache: Incomplete
    rpc_client: Incomplete
    namespace_id: Incomplete
    nacos_server_connector: Incomplete
    event_listener: Incomplete
    def __init__(self, client_config: ClientConfig, http_client: HttpAgent, service_info_cache: ServiceInfoCache) -> None: ...
    async def start(self) -> None: ...
    async def request_naming_server(self, request: AbstractNamingRequest, response_class): ...
    async def register_instance(self, service_name: str, group_name: str, instance: Instance): ...
    async def register_ephemeral_instance(self, service_name: str, group_name: str, instance: Instance): ...
    async def register_persistent_instance(self, service_name: str, group_name: str, instance: Instance): ...
    async def batch_register_instance(self, service_name: str, group_name: str, instances: list[Instance]) -> bool: ...
    async def deregister_instance(self, service_name: str, group_name: str, instance: Instance) -> bool: ...
    async def deregister_ephemeral_instance(self, service_name: str, group_name: str, instance: Instance) -> bool: ...
    async def deregister_persistent_instance(self, service_name: str, group_name: str, instance: Instance) -> bool: ...
    async def list_services(self, param: ListServiceParam) -> ServiceList: ...
    async def subscribe(self, service_name: str, group_name: str, clusters: str) -> Service | None: ...
    async def unsubscribe(self, service_name: str, group_name: str, clusters: str): ...
    async def close_client(self) -> None: ...
    def server_health(self): ...
