from _typeshed import Incomplete
from v2.nacos.naming.model.instance import Instance as Instance
from v2.nacos.naming.model.service import Service as Service
from v2.nacos.naming.util.naming_client_util import get_group_name as get_group_name, get_service_cache_key as get_service_cache_key
from v2.nacos.transport.connection_event_listener import ConnectionEventListener as ConnectionEventListener

class NamingGrpcConnectionEventListener(ConnectionEventListener):
    logger: Incomplete
    client_proxy: Incomplete
    registered_instance_cached: Incomplete
    subscribes: Incomplete
    lock: Incomplete
    def __init__(self, client_proxy) -> None: ...
    async def on_connected(self) -> None: ...
    async def on_disconnect(self) -> None: ...
    async def cache_instance_for_redo(self, service_name: str, group_name: str, instance: Instance) -> None: ...
    async def cache_instances_for_redo(self, service_name: str, group_name: str, instances: list[Instance]) -> None: ...
    async def remove_instance_for_redo(self, service_name: str, group_name: str) -> None: ...
    async def cache_subscribe_for_redo(self, full_service_name: str, cluster: str) -> None: ...
    async def remove_subscriber_for_redo(self, full_service_name: str, cluster: str) -> None: ...
