global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [prometheus:9090]
        labels:
          service: prometheus
          environment: development

  - job_name: otel-collector
    static_configs:
      - targets: [otel-collector:8888]
        labels:
          service: otel-collector
          environment: development

  - job_name: otel-application-metrics
    static_configs:
      - targets: [otel-collector:8889]
        labels:
          service: otel-application-metrics
          environment: development

  - job_name: spring-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - trip-attraction-service:24213
          - trip-hotel-service:24214
          - trip-inventory-service:24221
          - trip-itinerary-service:24219
          - trip-order-service:24222
          - trip-product-service:24220
          - trip-user-service:24217
        labels:
          environment: development

  - job_name: observability-services
    static_configs:
      - targets:
          - loki:3100
          - tempo:3200
          - alloy:12345
        labels:
          environment: development
