global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: otel-collector-exporter
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: otel-collector-self
    static_configs:
      - targets: ["otel-collector:8888"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: node-exporter
    static_configs:
      - targets: ["host.docker.internal:19100"]

  - job_name: celery-exporter
    static_configs:
      - targets: ["celery-exporter:9808"]

  - job_name: java-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - trip-attraction-service:24213
          - trip-hotel-service:24214
          - trip-inventory-service:24221
          - trip-itinerary-service:24219
          - trip-order-service:24222
          - trip-product-service:24220
          - trip-user-service:24217

  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]

  - job_name: tempo
    static_configs:
      - targets: ["tempo:3200"]
