from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field

from chat.common.parts import Part
from chat.utils.uuid import uuid7


class TaskState(StrEnum):
    """
    Defines the lifecycle states of a Task.
    """

    SUBMITTED = "submitted"
    WORKING = "working"
    INPUT_REQUIRED = "input-required"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    FAILED = "failed"
    REJECTED = "rejected"
    AUTH_REQUIRED = "auth-required"
    UNKNOWN = "unknown"


class Action(BaseModel):
    action_id: str = Field(
        default_factory=lambda: str(uuid7()),
        examples=["019a3b16-4759-767c-bc8c-eb3e094c71b9"],
    )
    message_id: str | None = Field(
        default=None,
        description="Optional ID of the Message that this Action contributes to.",
    )
    content: list[Part] | None = Field(
        default=None, description="Content parts of the Action."
    )
    action_type: Literal["reply", "tool_use", "pause"]
    created_at: datetime = Field(default_factory=datetime.now)


class TaskStatus(BaseModel):
    state: TaskState = Field(..., description="Current state of the Task.")
    updated_at: datetime = Field(
        default_factory=datetime.now,
        description="Timestamp of the last status update.",
    )
    action_id: str | None = Field(
        default=None,
        description="Optional ID of the Action associated with "
        "the latest Task status update.",
    )


class Task(BaseModel):
    """
    Represents a local/remote Task associated with a Conversation.

    [Status 0] ---> [Status 1] --[Action 0, 1]-> [Status 2] ---> ... ---> [Status N]
    """

    task_id: str = Field(
        alias="_id",
        default_factory=lambda: str(uuid7()),
        description="Remote Task's ID should be generated by the server agent.",
        examples=["019a3b16-4759-767c-bc8c-eb3e094c71b9"],
    )
    task_agent: str = Field(
        ...,
        description="Agent responsible for the Task.",
        examples=["chat-assistant", "review-summary"],
    )
    conversation_id: str = Field(
        ..., description="ID of the Conversation that this Task belongs to."
    )
    status: TaskStatus = Field(..., description="Current status of the Task.")
    history: list[str] = Field(
        default_factory=list[str],
        description="List of Message IDs representing the Task's history.",
    )
    actions: list[Action] = Field(
        default_factory=list[Action],
        description="List of actions associated with this Task.",
    )
    metadata: dict[str, Any] | None = Field(default=None)

    def is_terminal(self) -> bool:
        return self.status.state in {
            TaskState.COMPLETED,
            TaskState.CANCELLED,
            TaskState.FAILED,
            TaskState.REJECTED,
        }
