from _typeshed import Incomplete
from v2.nacos.common.client_config import ClientConfig as ClientConfig
from v2.nacos.common.constants import Constants as Constants
from v2.nacos.common.nacos_exception import INVALID_PARAM as INVALID_PARAM, NacosException as NacosException
from v2.nacos.nacos_client import NacosClient as NacosClient
from v2.nacos.naming.cache.service_info_cache import ServiceInfoCache as ServiceInfoCache
from v2.nacos.naming.model.instance import Instance as Instance
from v2.nacos.naming.model.naming_param import BatchRegisterInstanceParam as BatchRegisterInstanceParam, DeregisterInstanceParam as DeregisterInstanceParam, GetServiceParam as GetServiceParam, ListInstanceParam as ListInstanceParam, ListServiceParam as ListServiceParam, RegisterInstanceParam as RegisterInstanceParam, SubscribeServiceParam as SubscribeServiceParam
from v2.nacos.naming.model.service import Service as Service, ServiceList as ServiceList
from v2.nacos.naming.remote.naming_grpc_client_proxy import NamingGRPCClientProxy as NamingGRPCClientProxy
from v2.nacos.naming.util.naming_client_util import get_group_name as get_group_name

class NacosNamingService(NacosClient):
    namespace_id: Incomplete
    service_info_holder: Incomplete
    grpc_client_proxy: Incomplete
    def __init__(self, client_config: ClientConfig) -> None: ...
    @staticmethod
    async def create_naming_service(client_config: ClientConfig) -> NacosNamingService: ...
    async def register_instance(self, request: RegisterInstanceParam) -> bool: ...
    async def batch_register_instances(self, request: BatchRegisterInstanceParam) -> bool: ...
    async def deregister_instance(self, request: DeregisterInstanceParam) -> bool: ...
    async def update_instance(self, request: RegisterInstanceParam) -> bool: ...
    async def get_service(self, request: GetServiceParam) -> Service: ...
    async def list_services(self, request: ListServiceParam) -> ServiceList: ...
    async def list_instances(self, request: ListInstanceParam) -> list[Instance]: ...
    async def subscribe(self, request: SubscribeServiceParam) -> None: ...
    async def unsubscribe(self, request: SubscribeServiceParam) -> None: ...
    async def server_health(self) -> bool: ...
    async def shutdown(self) -> None: ...
