import abc
from abc import ABC, abstractmethod
from v2.nacos.config.model.config_param import HandlerParam as HandlerParam

class EncryptionPlugin(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def encrypt(self, handler_param: HandlerParam) -> HandlerParam: ...
    @abstractmethod
    def decrypt(self, handler_param: HandlerParam) -> HandlerParam: ...
    @abstractmethod
    def generate_secret_key(self, handler_param: HandlerParam) -> HandlerParam: ...
    @abstractmethod
    def algorithm_name(self): ...
    @abstractmethod
    def encrypt_secret_key(self, handler_param: HandlerParam) -> str: ...
    @abstractmethod
    def decrypt_secret_key(self, handler_param: HandlerParam) -> str: ...
