from _typeshed import Incomplete
from v2.nacos.common.constants import Constants as Constants
from v2.nacos.common.nacos_exception import INVALID_PARAM as INVALID_PARAM, NacosException as NacosException
from v2.nacos.config.encryption.kms_client import KmsClient as KmsClient
from v2.nacos.config.encryption.plugin.encryption_plugin import EncryptionPlugin as EncryptionPlugin
from v2.nacos.config.model.config_param import HandlerParam as HandlerParam
from v2.nacos.utils import aes_util as aes_util
from v2.nacos.utils.encode_util import decode_base64 as decode_base64, str_to_bytes as str_to_bytes

class KmsEncryptionPlugin(EncryptionPlugin):
    ALGORITHM: str
    kms_client: Incomplete
    def __init__(self, kms_client: KmsClient) -> None: ...
    @staticmethod
    def param_check(handler_param: HandlerParam): ...
    def encrypt(self, handler_param: HandlerParam) -> HandlerParam: ...
    def decrypt(self, handler_param: HandlerParam) -> HandlerParam: ...
    def generate_secret_key(self, handler_param: HandlerParam) -> HandlerParam: ...
    def algorithm_name(self) -> None: ...
    def encrypt_secret_key(self, handler_param: HandlerParam) -> str: ...
    def decrypt_secret_key(self, handler_param: HandlerParam) -> str: ...
