version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
    silent: true

  gen-proto:
    desc: Generate protobuf and gRPC codes
    sources:
      - ../contracts/protobuf/**/*.proto
    generates:
      - api/grpc/gen/**/*.go
    cmds:
      - buf generate

  build:
    desc: Build Docker image
    vars:
      PREFIX: '{{.PREFIX | default "tripsphere"}}'
      TAG: '{{.TAG | default "latest"}}'
    cmds:
      - docker build . -t {{.PREFIX}}/trip-review-service:{{.TAG}}

  build-aliyun:
    desc: Build Docker image with Aliyun Go mirror
    vars:
      PREFIX: '{{.PREFIX | default "tripsphere"}}'
      TAG: '{{.TAG | default "latest"}}'
    cmd: |
        docker build . -t {{.PREFIX}}/trip-review-service:{{.TAG}} \
        --build-arg ALPINE_MIRROR=s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g \
        --build-arg GOPROXY=https://mirrors.aliyun.com/goproxy/,direct

